name: py310
dependencies:
  - python=3.10
  - albumentations=1.3.0
  - einops=0.4.1
  - ipykernel=6.16.0
  - ipywidgets=7.7.1
  - pytorch=1.12.1
  - pytorch-lightning=1.6.5
  - scikit-learn=1.1.2
  - torchvision=0.13.0

